// NOTE Each new term in the fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1 2 3 5 8 13 21 34 55 89... By considering the terms in the fibonacci sequence whose values do not exceed four million, find the sum of even valued terms.
package main

import "fmt"

func fibonacci(n int) int {
	if n <= 1 {
		return n
	}
	return fibonacci(n-1) + fibonacci(n-2)
}

func main() {
	sum := 0
	for i := 1; i <= 40; i++ {
		fmt.Println(fibonacci(i))
		if fibonacci(i) < 4000000 {
			if fibonacci(i)%2 == 0 {
				sum += fibonacci(i)
			}
		} else {
			break
		}
	}

	fmt.Println(sum)
}
